### ISSUE TITLE
libnetcdff on Travis incompatible with recent gfortran

### ISSUE THREAD

**Issue by milancurcic** [umwm/umwm#1]
I struggle finding the right NetCDF Fortran library on Travis's Ubuntu (tried both trusty and xenial with no success). libnetcdff seems built with gfortran-4.8, which in turn does not support some "recent" features like `ieee_arithmetic`. gfortran-[5678] are available, but libnetcdff is incompatible with all of them.

@scivision @zbeekman Do you have experience with getting a more recent libnetcdff on Travis? You can see my yaml file here (mostly copied from yours :)):

https://github.com/umwm/umwm/blob/master/.travis.yml

Thanks!

**Comment by zbeekman** [comment]
Is your problem module file compatibility between the installed netcdf and the compiler, or linker issues?

I fear your only options are either to use a sudo enabled travis worker, find someones PPA providing netcdf compiled against recent GFortran, OR, build netcdf from source (and cache it, hopefully) as part of your build.

Homebrew, [as of 2.0, officially supports linux/linux brew](https://brew.sh/2019/02/02/homebrew-2.0.0/). Not all packages in linux brew are bottled, and you almost always need to build libc from source, so this probably won't help you, unless you can cache your homebrew/linuxbrew packages, and incrementally build out your toolchain.

**Comment by scivision** [comment]
I think the simplest and most general solution is to make a Docker image Ubuntu 18.04, Gfortran 7 will work with netcdf as its all system libs. It will run on Travis.
I think you've seen my docker-fortran repo?
https://github.com/scivision/docker-fortran
That tells how to do it from scratch.

**Comment by zbeekman** [comment]
Yeah that's probably the most convenient way to approach it once you have a
decent docker image setup and pushed to Docker hub.

Also, the latest Docker on macOS Mojave seems VERY buggy/resource hungry
now. I get zombie daemons slurping up CPU cycles even after quitting docker
desktop.

**Comment by milancurcic** [comment]
The problem is module file compatibility. Thanks both. It looks like my best option is Michael's docker approach. I have seen it before, pardon my laziness :). I will give this a shot tomorrow.
